# Generated by Django 6.0.1 on 2026-01-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False, unpack_ipv4=True)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BDayIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Запрошено_в_')),
                ('birth_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.birthday')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ip')),
            ],
        ),
    ]
