# Generated by Django 6.0.1 on 2026-01-16 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdayip',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_days', related_query_name='birthday', to='main.ip'),
        ),
    ]
