# Generated by Django 6.0.1 on 2026-01-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bdayip_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='comment',
            field=models.CharField(default='', max_length=32),
        ),
    ]
